apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nginx
spec:
  rules:
  - host: 13.235.196.56.nip.io
    http:
      paths:
      - backend:
          serviceName: nginx
          servicePort: 8080
        path: /test
